In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
from sklearn import datasets

In [26]:
df = pd.read_csv('abt_app.csv',sep='\t')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11437 entries, 0 to 11436
Columns: 219 entries, cid to cross_app_n_installments
dtypes: float64(206), int64(2), object(11)
memory usage: 19.1+ MB

In [28]:
df.head()

,cid,aid,product,period,act_age,act_cc,act_loaninc,app_income,app_loan_amount,app_n_installments,...,default3,default6,default9,default12,default_cross3,default_cross6,default_cross9,default_cross12,cross_app_loan_amount,cross_app_n_installments
0,1330,css1975010100098,css,197501,45.0,0.326905,1.530456,3267.0,5000.0,24.0,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2179,css1975010100120,css,197501,42.0,0.538908,2.903600,1722.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,146,css1975010200014,css,197501,59.0,0.543742,3.364738,1486.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5000.0,24.0
3,479,css1975010200047,css,197501,63.0,0.587702,3.236246,1545.0,5000.0,24.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4514,css1975010200151,css,197501,48.0,0.436407,1.506932,3318.0,5000.0,24.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
delete =['aid','cid','cross_aid','period','default3','default6','default9','default_cross3','default_cross6','default_cross9','default_cross12']
df=df.drop(delete,axis=1)

In [30]:
df.head()

,product,act_age,act_cc,act_loaninc,app_income,app_loan_amount,app_n_installments,app_number_of_children,app_spendings,app_installment,...,ags12_Min_CMaxA_Due,act12_n_arrears,act12_n_arrears_days,act12_n_good_days,decision,cross_response,cross_after_monhs,default12,cross_app_loan_amount,cross_app_n_installments
0,css,45.0,0.326905,1.530456,3267.0,5000.0,24.0,3.0,860.0,208.0,...,0.0,10.0,2.0,4.0,A,0.0,NaN,1.0,NaN,NaN
1,css,42.0,0.538908,2.903600,1722.0,5000.0,24.0,1.0,720.0,208.0,...,0.0,0.0,0.0,1.0,A,0.0,NaN,0.0,NaN,NaN
2,css,59.0,0.543742,3.364738,1486.0,5000.0,24.0,2.0,600.0,208.0,...,0.0,4.0,0.0,1.0,A,1.0,4.0,0.0,5000.0,24.0
3,css,63.0,0.587702,3.236246,1545.0,5000.0,24.0,0.0,700.0,208.0,...,0.0,3.0,0.0,4.0,A,0.0,NaN,0.0,NaN,NaN
4,css,48.0,0.436407,1.506932,3318.0,5000.0,24.0,2.0,1240.0,208.0,...,0.0,0.0,0.0,10.0,A,0.0,NaN,1.0,NaN,NaN

In [33]:
from AmaFree import AdvancedScorecardBuilder as asb

In [40]:
abt = asb(df,'default12')

feature product removed - one value in column
feature app_loan_amount removed - one value in column
feature app_n_installments removed - one value in column
feature app_installment removed - one value in column
feature app_char_branch removed - one value in column
feature act_cus_active removed - one value in column
feature decision removed - one value in column

In [36]:
df = df.dropna(subset=['default12'])

In [39]:
df['default12'] = df['default12'].astype(np.int64)

In [46]:
abt.data

,act_age,act_cc,act_loaninc,app_income,app_number_of_children,app_spendings,app_char_gender,app_char_job_code,app_char_marital_status,app_char_city,...,ags12_Max_CMaxA_Due,agr12_Min_CMaxA_Due,ags12_Min_CMaxA_Due,act12_n_arrears,act12_n_arrears_days,act12_n_good_days,cross_response,cross_after_monhs,cross_app_loan_amount,cross_app_n_installments
0,45.0,0.326905,1.530456,3267.0,3.0,860.0,Female,Permanent,Maried,Big,...,3.0,0.0,0.0,10.0,2.0,4.0,0.0,NaN,NaN,NaN
1,42.0,0.538908,2.903600,1722.0,1.0,720.0,Male,Permanent,Maried,Big,...,0.0,NaN,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
2,59.0,0.543742,3.364738,1486.0,2.0,600.0,Female,Retired,Maried,Big,...,1.0,0.0,0.0,4.0,0.0,1.0,1.0,4.0,5000.0,24.0
3,63.0,0.587702,3.236246,1545.0,0.0,700.0,Female,Retired,Divorced,Big,...,2.0,NaN,0.0,3.0,0.0,4.0,0.0,NaN,NaN,NaN
4,48.0,0.436407,1.506932,3318.0,2.0,1240.0,Female,Owner company,Maried,Big,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,NaN,NaN,NaN
5,49.0,0.220888,3.001200,1666.0,2.0,160.0,Male,Permanent,Maried,Medium,...,2.0,0.0,0.0,5.0,0.0,10.0,1.0,5.0,5000.0,24.0
6,51.0,0.783217,3.885004,1287.0,2.0,800.0,Female,Retired,Divorced,Large,...,0.0,0.0,0.0,0.0,0.0,11.0,0.0,NaN,NaN,NaN
7,55.0,0.622222,5.291005,945.0,0.0,380.0,Female,Contract,Divorced,Medium,...,0.0,NaN,0.0,0.0,0.0,3.0,0.0,NaN,NaN,NaN
8,60.0,0.634170,2.461841,2031.0,0.0,1080.0,Female,Retired,Maried,Large,...,0.0,0.0,0.0,0.0,0.0,8.0,0.0,NaN,NaN,NaN
9,60.0,0.620979,3.496503,1430.0,0.0,680.0,Female,Retired,Maried,Large,...,3.0,0.0,0.0,6.0,0.0,9.0,0.0,NaN,NaN,NaN
11,73.0,0.773869,12.562814,398.0,0.0,100.0,Male,Retired,Widowed,Big,...,0.0,NaN,0.0,0.0,0.0,2.0,0.0,NaN,NaN,NaN
14,59.0,0.589235,2.360718,2118.0,3.0,1040.0,Male,Permanent,Maried,Large,...,1.0,0.0,0.0,4.0,0.0,4.0,1.0,4.0,5000.0,24.0
15,50.0,0.285105,2.134016,2343.0,1.0,460.0,Female,Permanent,Maried,Medium,...,2.0,0.0,0.0,8.0,1.0,3.0,0.0,NaN,NaN,NaN
16,54.0,0.829932,8.503401,588.0,1.0,280.0,Female,Retired,Maried,Medium,...,2.0,0.0,0.0,9.0,1.0,7.0,0.0,NaN,NaN,NaN
18,59.0,0.444911,2.623295,1906.0,0.0,640.0,Male,Contract,Maried,Medium,...,1.0,NaN,0.0,3.0,0.0,1.0,0.0,NaN,NaN,NaN
19,48.0,0.304915,2.507523,1994.0,0.0,400.0,Female,Permanent,Maried,Big,...,1.0,0.0,0.0,7.0,0.0,1.0,0.0,NaN,NaN,NaN
22,62.0,0.752593,7.407407,675.0,3.0,300.0,Male,Retired,Maried,Medium,...,3.0,0.0,0.0,7.0,0.0,7.0,0.0,NaN,NaN,NaN
24,69.0,0.795181,7.530120,664.0,1.0,320.0,Female,Retired,Widowed,Medium,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
25,46.0,0.140639,2.283105,2190.0,1.0,100.0,Female,Permanent,Divorced,Small,...,2.0,0.0,0.0,7.0,0.0,9.0,0.0,NaN,NaN,NaN
26,71.0,0.715177,5.197505,962.0,2.0,480.0,Male,Retired,Divorced,Large,...,3.0,0.0,0.0,10.0,0.0,5.0,0.0,NaN,NaN,NaN
28,49.0,0.479070,1.453488,3440.0,2.0,1440.0,Female,Permanent,Maried,Small,...,1.0,0.0,0.0,8.0,0.0,6.0,1.0,4.0,5000.0,24.0
29,72.0,0.680851,4.432624,1128.0,0.0,560.0,Female,Retired,Widowed,Big,...,1.0,0.0,0.0,7.0,0.0,7.0,0.0,NaN,NaN,NaN
30,44.0,0.366489,1.568874,3187.0,1.0,960.0,Female,Permanent,Maried,Big,...,0.0,NaN,0.0,0.0,0.0,7.0,0.0,NaN,NaN,NaN
32,52.0,0.408464,2.299908,2174.0,0.0,680.0,Female,Permanent,Divorced,Small,...,1.0,0.0,0.0,5.0,0.0,8.0,0.0,NaN,NaN,NaN
33,66.0,0.559546,3.150599,1587.0,0.0,680.0,Female,Retired,Divorced,Big,...,2.0,0.0,0.0,10.0,2.0,5.0,0.0,NaN,NaN,NaN
34,57.0,0.448501,3.259452,1534.0,1.0,480.0,Female,Retired,Maried,Medium,...,3.0,0.0,0.0,9.0,0.0,1.0,0.0,NaN,NaN,NaN
35,66.0,0.619130,2.898551,1725.0,0.0,860.0,Male,Contract,Divorced,Medium,...,7.0,NaN,0.0,7.0,0.0,4.0,0.0,NaN,NaN,NaN
37,61.0,0.348616,2.269632,2203.0,0.0,560.0,Female,Retired,Divorced,Medium,...,1.0,0.0,0.0,3.0,0.0,7.0,1.0,4.0,5000.0,24.0
38,61.0,0.403895,2.562788,1951.0,0.0,580.0,Female,Retired,Maried,Big,...,1.0,0.0,0.0,10.0,0.0,3.0,0.0,NaN,NaN,NaN
39,51.0,0.268349,1.660578,3011.0,2.0,600.0,Female,Permanent,Maried,Big,...,0.0,0.0,0.0,0.0,0.0,11.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11405,51.0,0.271019,2.472799,2022.0,1.0,340.0,Female,Permanent,Maried,Medium,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
11406,71.0,0.697201,6.361323,786.0,0.0,340.0,Female,Retired,Widowed,Big,...,0.0,NaN,0.0,0.0,0.0,3.0,0.0,NaN,NaN,NaN
11407,67.0,0.407035,3.140704,1592.0,0.0,440.0,Female,Permanent,Maried,Small,...,0.0,0.0,0.0,0.0,0.0,9.0,0.0,NaN,NaN,NaN
11408,82.0,0.499425,2.876870,1738.0,1.0,660.0,Female,Retired,Divorced,Big,...,1.0,0.0,0.0,3.0,0.0,6.0,1.0,4.0,5000.0,24.0
11409,89.0,0.843615,7.173601,697.0,0.0,380.0,Female,Retired,Widowed,Big,...,1.0,0.0,0.0,2.0,0.0,7.0,0.0,NaN,NaN,NaN
11410,77.0,0.608850,4.424779,1130.0,1.0,480.0,Female,Retired,Widowed,Big,...,1.0,0.0,0.0,1.0,0.0,5.0,1.0,5.0,5000.0,24.0
11411,84.0,0.522489,3.080715,1623.0,0.0,640.0,Female,Retired,Widowed,Small,...,0.0,0.0,0.0,0.0,0.0,3.0,1.0,4.0,5000.0,24.0
11412,74.0,0.827869,5.122951,976.0,0.0,600.0,Female,Retired,Widowed,Big,...,2.0,0.0,0.0,7.0,0.0,9.0,1.0,4.0,5000.0,24.0
11413,70.0,0.974874,12.562814,398.0,0.0,180.0,Female,Retired,Maried,Medium,...,3.0,NaN,0.0,3.0,0.0,0.0,0.0,NaN,NaN,NaN
11415,68.0,0.837920,7.645260,654.0,0.0,340.0,Male,Retired,Widowed,Big,...,0.0,NaN,0.0,0.0,0.0,3.0,0.0,NaN,NaN,NaN
11416,66.0,0.820513,6.747638,741.0,0.0,400.0,Female,Retired,Maried,Big,...,1.0,0.0,0.0,1.0,0.0,9.0,0.0,NaN,NaN,NaN
11417,71.0,0.657074,5.995204,834.0,0.0,340.0,Female,Retired,Widowed,Big,...,0.0,NaN,0.0,0.0,0.0,6.0,0.0,NaN,NaN,NaN
11418,54.0,0.358812,3.158560,1583.0,0.0,360.0,Female,Permanent,Maried,Big,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,NaN,NaN,NaN
11419,55.0,0.540782,2.793296,1790.0,1.0,760.0,Female,Permanent,Maried,Large,...,2.0,0.0,0.0,8.0,1.0,5.0,0.0,NaN,NaN,NaN
11420,89.0,0.349802,2.470356,2024.0,0.0,500.0,Female,Retired,Divorced,Medium,...,2.0,1.0,1.0,12.0,0.0,5.0,1.0,4.0,5000.0,24.0
11421,66.0,0.713458,3.219575,1553.0,1.0,900.0,Female,Permanent,Widowed,Medium,...,3.0,0.0,0.0,6.0,0.0,6.0,0.0,NaN,NaN,NaN
11422,66.0,0.704403,7.861635,636.0,2.0,240.0,Female,Retired,Maried,Big,...,3.0,0.0,0.0,10.0,0.0,3.0,0.0,NaN,NaN,NaN
11423,78.0,0.742857,7.936508,630.0,1.0,260.0,Female,Retired,Widowed,Large,...,1.0,0.0,0.0,2.0,0.0,4.0,1.0,4.0,5000.0,24.0
11424,76.0,0.950820,13.661202,366.0,0.0,140.0,Female,Retired,Maried,Medium,...,2.0,0.0,0.0,10.0,1.0,6.0,1.0,4.0,5000.0,24.0
11425,52.0,0.301928,2.754821,1815.0,1.0,340.0,Male,Permanent,Maried,Big,...,1.0,0.0,0.0,4.0,0.0,4.0,0.0,NaN,NaN,NaN
11426,81.0,0.879915,5.313496,941.0,0.0,620.0,Female,Retired,Divorced,Big,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,NaN,NaN,NaN
11427,64.0,0.747613,6.821282,733.0,0.0,340.0,Male,Retired,Maried,Big,...,1.0,0.0,0.0,2.0,0.0,9.0,1.0,4.0,5000.0,24.0
11428,32.0,0.275490,3.376097,1481.0,1.0,200.0,Male,Contract,Maried,Big,...,6.0,NaN,0.0,6.0,0.0,0.0,0.0,NaN,NaN,NaN
11429,87.0,0.720801,5.561735,899.0,0.0,440.0,Male,Retired,Widowed,Big,...,0.0,0.0,0.0,0.0,0.0,11.0,0.0,NaN,NaN,NaN
11430,79.0,0.708081,2.748763,1819.0,0.0,1080.0,Female,Retired,Widowed,Medium,...,3.0,0.0,0.0,5.0,1.0,6.0,0.0,NaN,NaN,NaN
11431,65.0,0.884097,13.477089,371.0,0.0,120.0,Female,Retired,Divorced,Medium,...,5.0,NaN,0.0,6.0,1.0,0.0,0.0,NaN,NaN,NaN
11432,81.0,0.378284,2.918856,1713.0,1.0,440.0,Female,Retired,Widowed,Big,...,0.0,0.0,0.0,0.0,0.0,2.0,1.0,4.0,5000.0,24.0
11433,72.0,0.685067,3.538570,1413.0,2.0,760.0,Female,Retired,Widowed,Medium,...,2.0,0.0,0.0,7.0,1.0,1.0,1.0,4.0,5000.0,24.0
11435,90.0,0.697761,4.664179,1072.0,0.0,540.0,Male,Retired,Widowed,Big,...,1.0,0.0,0.0,6.0,0.0,5.0,1.0,4.0,5000.0,24.0
11436,71.0,0.404114,3.024803,1653.0,0.0,460.0,Female,Retired,Widowed,Small,...,2.0,0.0,0.0,3.0,0.0,3.0,1.0,4.0,5000.0,24.0

In [47]:
abt.fit()

You have less then 0.05 empty values in ags3_Mean_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in ags3_Max_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in ags3_Min_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in agr3_Mean_CMaxA_Due. I change them by mean value
You have less then 0.05 empty values in agr3_Max_CMaxA_Due. I change them by mean value
You have less then 0.05 empty values in agr3_Min_CMaxA_Due. I change them by mean value
You have less then 0.05 empty values in ags6_Mean_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in ags6_Max_CMaxA_Days. I change them by mean value
You have less then 0.05 empty values in ags6_Min_CMaxA_Days. I change them by mean value
I removed agr9_Min_CMaxI_Due - no binns
I removed ags9_Min_CMaxI_Due - no binns
I removed agr12_Max_CMaxI_Days - no binns
I removed agr12_Min_CMaxI_Due - no binns
I removed ags12_Min_CMaxI_Due - no binns
I removed agr12_Min_CMaxC_Due - no binns
I removed ags12_Min_CMaxC_Due - no binns
I removed agr12_Min_CMaxA_Due - no binns

In [50]:
abt.get_scorecard()

                                       label                 variable  score
0          (not missing) and act_age <= 45.5                  act_age      5
1                     45.5 < act_age <= 60.5                  act_age     12
2                     60.5 < act_age <= 80.5                  act_age     19
3                             80.5 < act_age                  act_age     33
4               app_char_job_code = Contract        app_char_job_code      5
5          app_char_job_code = Owner company        app_char_job_code     55
6              app_char_job_code = Permanent        app_char_job_code     73
7                app_char_job_code = Retired        app_char_job_code     76
8          app_char_marital_status = Singiel  app_char_marital_status      5
9         app_char_marital_status = Divorced  app_char_marital_status     22
10          app_char_marital_status = Maried  app_char_marital_status     31
11         app_char_marital_status = Widowed  app_char_marital_status     36
12                       1.498 < act_call_cc              act_call_cc      5
13              1.266 < act_call_cc <= 1.498              act_call_cc     29
14               0.44 < act_call_cc <= 1.266              act_call_cc     43
15     (not missing) and act_call_cc <= 0.44              act_call_cc     53
16             0.5 < act_ccss_n_statC <= 7.5         act_ccss_n_statC      5
17                   act_ccss_n_statC <= 0.5         act_ccss_n_statC      9
18                                   missing         act_ccss_n_statC     31
19            7.5 < act_ccss_n_statC <= 16.5         act_ccss_n_statC     56
20                   16.5 < act_ccss_n_statC         act_ccss_n_statC     98
21                   0.046 < act_ccss_dueutl          act_ccss_dueutl      5
22          0.023 < act_ccss_dueutl <= 0.046          act_ccss_dueutl     32
23          0.009 < act_ccss_dueutl <= 0.023          act_ccss_dueutl     51
24                                   missing          act_ccss_dueutl     89
25                  act_ccss_dueutl <= 0.009          act_ccss_dueutl     90
26               1.083 < agr6_Mean_CMaxI_Due      agr6_Mean_CMaxI_Due      5
27      0.583 < agr6_Mean_CMaxI_Due <= 1.083      agr6_Mean_CMaxI_Due     32
28       0.25 < agr6_Mean_CMaxI_Due <= 0.583      agr6_Mean_CMaxI_Due     36
29                                   missing      agr6_Mean_CMaxI_Due     45
30               agr6_Mean_CMaxI_Due <= 0.25      agr6_Mean_CMaxI_Due     46
31            14.775 < ags12_Mean_CMaxI_Days    ags12_Mean_CMaxI_Days      5
32                                   missing    ags12_Mean_CMaxI_Days      9
33           ags12_Mean_CMaxI_Days <= 13.211    ags12_Mean_CMaxI_Days     11
34  13.348 < ags12_Mean_CMaxI_Days <= 14.775    ags12_Mean_CMaxI_Days     16
35  13.211 < ags12_Mean_CMaxI_Days <= 13.348    ags12_Mean_CMaxI_Days     32

In [52]:
abt.model_info_

{'F1': 0.7498176513493799,
 'Precision': 0.8006230529595015,
 'Recall': 0.7050754458161865,
 'acc': 0.7681649205812775,
 'coef': {'act_age': 0.7848358485016468,
  'act_call_cc': 1.412598701875752,
  'act_ccss_dueutl': 0.911629673136728,
  'act_ccss_n_statC': 0.898750599787923,
  'agr6_Mean_CMaxI_Due': 1.1075907060890149,
  'ags12_Mean_CMaxI_Days': 1.165291428501025,
  'app_char_job_code': 1.269236791325133,
  'app_char_marital_status': 0.8422150157108814},
 'features': ['act_age',
  'app_char_job_code',
  'app_char_marital_status',
  'act_call_cc',
  'act_ccss_n_statC',
  'act_ccss_dueutl',
  'agr6_Mean_CMaxI_Due',
  'ags12_Mean_CMaxI_Days'],
 'gini': 0.664063271794727,
 'intercept': array([0.30587203]),
 'model': 'LogisticRegressionCV',
 'p_value': {'act_age': 0.0,
  'act_call_cc': 0.0,
  'act_ccss_dueutl': 0.0,
  'act_ccss_n_statC': 0.0,
  'agr6_Mean_CMaxI_Due': 0.0,
  'ags12_Mean_CMaxI_Days': 0.0,
  'app_char_job_code': 0.0,
  'app_char_marital_status': 0.0}}

In [54]:
abt.html_report('report.html')